### ISSUE TITLE
Add Running the Program instructions for Mac.

### ISSUE THREAD

**Issue by dominicduffin1** [dominicduffin1/python-turtle-art-canvas#1]
# Please describe the issue
The Readme needs to contain instructions for running the program on Mac.

## Steps:

Work out and test the commands needed to run the program on Mac.

Add instructions to the Readme.

# Please link to the file(s) involved
[Readme](https://github.com/dominicduffin1/python-turtle-art-canvas#readme)

**Comment by ClJarvis** [comment]
@dominicduffin1 I'm interested writing the Mac instructions. If I remember right you demoed this sometime. Is there a video of the demo?

**Comment by dominicduffin1** [comment]
@ClJarvis Thank you, I've assigned you!

There isn't a demo for this project because I only started it this month, but at the moment it should simply render an empty turtle window, screenshot attached from my Windows computer

![Screenshot (24)](https://user-images.githubusercontent.com/26224873/135897451-2738895c-df0d-478b-be49-c450b1c0248f.png)
r

**Comment by ClJarvis** [comment]
Ok I got that far. I saw the empty turtle using a Mac.

**Comment by dominicduffin1** [comment]
@ClJarvis In that case, if you ca put in a pull request with instructions in the Mac section that would be great!
